### ISSUE TITLE
0.5.2 fails `pip install` on Python 2.7

### ISSUE THREAD

**Issue by PhilMiller** [lmmentel/mendeleev#10]
The change in #8 makes the latest version uninstallable on Python 2.7, with the following error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Z0AaPx/mendeleev/setup.py", line 68, in <module>
        setup_package()
      File "/tmp/pip-build-Z0AaPx/mendeleev/setup.py", line 56, in setup_package
        long_description=readme(),
      File "/tmp/pip-build-Z0AaPx/mendeleev/setup.py", line 39, in readme
        with open('README.rst', encoding='utf8') as freadme:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Z0AaPx/mendeleev/
```

Don't know if you care to keep supporting older Python, but we've just got migration to Python 3 in progress, but still not complete.

As I look at what's non-ASCII in README.rst, I realize it's your name in the bibtex citation. If it were anything else, I'd put up a pull request to make encoding-specification unnecessary.

**Comment by PhilMiller** [comment]
Ah, per https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2 it should be possible to use `io.open` and have it work at least as far back as 2.6

**Comment by lmmentel** [comment]
Hi @PhilMiller,

Thanks for reporting the issue. I wasn't planning on breaking the python2.7 compatibility but there was a recent patch restores compatibility with windows and python3.x broke 2.7. I'm happy to accept a pull request that doesn't break the current compatibility and restores python2.7 but since python2.7 [reached it's end of life](https://www.python.org/dev/peps/pep-0373/) I'm not planning to support it.

I did a quick check, following the solution you highlighted but got an error when installing pandas, since it tries to install the newest version which [does not support python2.7 anymore](https://github.com/pandas-dev/pandas/pull/20540/files). I guess it'll be more and more difficult to support 2.7. 

Have you made it work on your end after applying the change?

**Comment by PhilMiller** [comment]
I haven't made it work on my system, no. It looks like my client's code declares a dependency on pandas, but it may be pinned to an older version somewhere that I haven't seen.

You can probably just let this drop - 0.5.1 is probably fine for now, and we're migrating forward anyway.

Thanks.

**Comment by lmmentel** [comment]
Alright, thanks for getting back with the information. Once I update the docs about the python2.7 incompatibility I'll close this issue.
