### ISSUE TITLE
boiling and melting points in the elements table?

### ISSUE THREAD

**Issue by vthost** [lmmentel/mendeleev#111]
## Describe the bug
The documentation about the bulk data shows boiling and melting points in the elements table, but I do not have them when I access it as described in the examples in the documentation.

## To Reproduce
exactly as described at https://mendeleev.readthedocs.io/en/latest/notebooks/bulk_data_access.html

## Expected behavior
the two properties in the table

## Specification

mendleev version: mendeleev-0.13.1-py3-none-any.whl

## Additional context
I'd just need to know how I can access the properties. Have they been moved to another table maybe?

**Comment by lmmentel** [comment]
Hi Veronika, thanks for reporting this back. It seems I haven't updated all the docs when making the change for version 0.12.0. You are right, boiling and melting points are since then in a separate table to accommodate cases where some elements have allotropes with different properties. The new table is called `phasetransitions` and in addition has _critical temperatere_, _critial pressure_, and _temperature_ and _pressure_ at _triple point_.

Right now you cannot really use `fetch_table` to get the table (something that should be an easy fix) however here's a workaround using pandas to extract the data:

```python
import pandas as pd
from mendeleev.db import get_engine

engine  = get_engine()
pt = pd.read_sql_table("phasetransitions", engine)
```
which return a datafame with

```python
      id  atomic_number  boiling_point  melting_point  ...  critical_pressure  triple_point_temperature  triple_point_pressure  allotrope
0      1             89       3473.150       1323.150  ...                NaN                       NaN                    NaN       None
1      2             13       2792.150        933.473  ...                NaN                       NaN                    NaN       None
2      3             95            NaN       1449.150  ...                NaN                       NaN                    NaN       None
3      4             51       1860.150        903.778  ...                NaN                       NaN                    NaN       gray
4      5             18         87.302         83.810  ...              4.863                   83.8058                  68.89       None
..   ...            ...            ...            ...  ...                ...                       ...                    ...        ...
103  104             54        165.051        161.400  ...              5.842                  161.4050                  81.77       None
104  105             70       1469.150       1097.150  ...                NaN                       NaN                    NaN       None
105  106             39       3618.150       1795.150  ...                NaN                       NaN                    NaN       None
106  107             30       1180.150        692.677  ...                NaN                       NaN                    NaN       None
107  108             40       4679.150       2127.150  ...                NaN                       NaN                    NaN       None

[108 rows x 9 columns]
```

Let me know if that helps.

**Comment by vthost** [comment]
Thank you so much for the fast reply!
