### ISSUE TITLE
Installing meedelev from pip uninstalls my Numpy 1.20.3

### ISSUE THREAD

**Issue by erwanp** [lmmentel/mendeleev#125]
## Describe the bug

```pip install meedelev``` uninstalls my numpy version (1.20.3)

This might be due to the requirements ```pyfiglet<0.9,>=0.8.post1``` 

## Specification

- mendleev version 0.14
- python version 3.9
- platform Win

**Comment by lmmentel** [comment]
Hey, thanks for reporting back. Latest `mendeleev` requires `numpy>=1.21` so if you have an earlier version it'll try to update it. 

A good idea might be to update your numpy version since 1.20.3 is already more that 2 years old (latest numpy is 1.25.2). You could also try isolating your installation with a virtual environment.

**Comment by erwanp** [comment]
Alright I thought I was more up-to-date. Closing !
