### ISSUE TITLE
Oxides for each element

### ISSUE THREAD

**Issue by kaylai** [lmmentel/mendeleev#17]
**Is your feature request related to a problem? Please describe.**
I am a geologist looking to build python tools for other geologists. This library is extremely helpful and amazing, so first off kudos to the devs! Geological data tends to describe chemical compositions in terms of oxides, so I find myself needing to switch between describing a sample as elements (e.g., Si, Ti, P...) and oxides (e.g., SiO2, TiO2, P2O5).

**Describe the solution you'd like**
I realize there are some details to work out, but if it were possible to access information about what oxides exist for each element, that would be great. For example another column in the ptable accessed with:
```python
from mendeleev import get_table
ptable = get_table('elements')
```

such that 'Si' would map to 'SiO2' and so on.

**Describe alternatives you've considered**
Maybe there is already a straightforward way to do this that I have simply overlooked. If so, my apologies!

**Comment by kalvdans** [comment]
The oxides of elements could be constructed from the oxidation state, so I would say the functionality exist already :)
```python
for z in range(1,93): 
     e = mendeleev.element(z) 
     for ox in e.oxistates: 
         if ox and ox > 0: 
             print(f"{e.symbol}2O{ox}") 
```

**Comment by kaylai** [comment]
This is amazing, thank you!

**Comment by kaylai** [comment]
Closed this but then realized... with that code, some of the oxides are unbalanced. For example, I get Si2O4 but also Si2O2. But, I don't see SiO2, which is the oxide I was expecting.

**Comment by kaylai** [comment]
I thought this was the complete answer, but if you'll humor me...

Your solution doesn't work universally for all oxides, since the number of cations to the number of O's obviously depends on the oxidation state. With your solution you get:

```
H2O1
Li2O1
Be2O2
B2O3
C2O4
C2O2
N2O5
N2O4
N2O3
N2O2
N2O1
Na2O1
Mg2O2
Al2O3
Si2O4
Si2O2
...
```

I got a bit closer with this hack, but it's not inclusive, and I know there is a mathematical way to create an oxide formula from the oxidation states, but for some reason this problem is eluding me... maybe my brain has fogged...

With this:
```python
for z in range(1,93): 
	e = mendeleev.element(z) 
	for ox in e.oxistates: 
		if ox and ox > 0: 
			if ox == 2:
				print(f"{e.symbol}O")
			cation_number = int(ox/2)
			if cation_number == 2:
				print(f"{e.symbol}O{cation_number}") 
```

You get something like:
```
BeO
CO2
CO
NO2
NO2
NO
MgO
SiO2
SiO
PO2
...
```

I'm also struggling to think of a way to represent the oxide that I want (what is stable in rocks). For example, getting SiO2 over SiO.... I know I can simply hard code a dict to map these a la `{'Si':'SiO2'}`, but I'm sure there is a pythonic way to do it. 

Feel free to close this in any event, if you feel it's not relevant to mendeleev!

**Comment by kalvdans** [comment]
Interesting! Do you have some more information on the process of extracting the oxides from the rock? (I've heard one metgod is called 4-acid.) I think that understanding the process will give us a clue to which oxidation number to use.

**Comment by lmmentel** [comment]
@kaylai thanks a lot for taking the time and submitting this issue :+1: 

This is an interesting use case and I would be curious to know how would you prefer to access/use this data? I'm asking since there are at least two alternatives here:

1. A method in the `Element` class for getting the possible oxides for a given element. This is probably more useful if you are dealing with individual elements or small collections elements.
2. A method for producing a table (or pandas DataFrame) with desired data and an additional oxide column

Apart of that, here is how I would tackle getting all the oxides for the elements
```python
from mendeleev import element
import math

def coeffs(a, b=2):
    """
    Return oxide coefficients from oxidation states
    """
    lcm = abs(a * b) // math.gcd(a, b)
    return lcm // a, lcm // b

for e in element(list(range(1, 80))):
    # calculate coefficients
    oxide_coeffs = [coeffs(ox) for ox in e.oxistates if ox > 0]
    # convert to strings and replace 1 with empty string
    normal_coeffs = [[str(c) if c != 1 else '' for c in t] for t in oxide_coeffs]
    oxides = [f"{e.symbol}{cme}O{co}" for cme, co in normal_coeffs]
    if oxides:
        print(e.name, oxides)
```
which produces
```
Hydrogen ['H2O']
Lithium ['Li2O']
Beryllium ['BeO']
Boron ['B2O3']
Carbon ['CO2', 'CO']
Nitrogen ['N2O5', 'NO2', 'N2O3', 'NO', 'N2O']
Sodium ['Na2O']
Magnesium ['MgO']
Aluminum ['Al2O3']
Silicon ['SiO2', 'SiO']
Phosphorus ['P2O5', 'P2O3']
Sulfur ['SO3', 'SO2', 'SO']
Chlorine ['Cl2O7', 'Cl2O5', 'Cl2O3', 'Cl2O']
Potassium ['K2O']
Calcium ['CaO']
Scandium ['Sc2O3']
Titanium ['TiO2', 'Ti2O3', 'TiO']
Vanadium ['V2O5', 'VO2', 'V2O3', 'VO']
Chromium ['CrO3', 'Cr2O3', 'CrO']
...
```

There a few nuances here since I'm filtering only the positive oxidation states to produce oxides which means that some of the elements are skipped in the list (where oxides are not possible). Also for elements with multiple oxidation states there are multiple oxides possible and if I understand correctly you would want one representative. This could probably further filtered based on geological abundances of oxides but I don't have that data. A simpler and probably less useful filter would be to take the oxide with the smallest/largest oxidation state. Let me know what you think since you are the expert here.

BTW If you are interested in generating custom data tables (or DataFrames) take a look at the  [utils modue](https://github.com/lmmentel/mendeleev/blob/master/mendeleev/utils.py) where I have some methods for doing something similar. I'm mentioning this since it might be relevant but is not yet documented.

**Comment by kaylai** [comment]
Hi all,

First off, thanks so much for taking the time to humor me with this request. @lmmentel your solution is exactly what I had in mind save any "geologic" filtering! What I would like to use this data for is primarily for transforming how chemical compositions of rocks are represented. Geologists almost always report rock compositions as wt% oxides, but some thermodynamic calculations may require, for example, mole fraction in terms of cations. I'm working on a couple of projects that require methods for "translating" user data (chemical compositions of rocks) in order to do various calculations. What my colleagues and I have done thus far is to create a rather restricted element and oxide list and then have a dict that maps the two, for example:

```python
elements = ["Si", "Ti", etc...]
oxides = ["SiO2", "TiO2", etc...]
oxides_to_elements = {"SiO2": "Si", "TiO2": "Ti", etc...}
```

Since there are only a handful of oxides/elements we expect users to pass (or indeed, often we only _care_ about a small subset of these so can ignore any trace elements), this is almost always totally sufficient. But, I'd like to build a more generic tool for these kinds of things, and it seems like mendeleev has already done most of the work for me. I would just need to add some geologic specificities atop what you've already created.

I need to give some thought to whether there is a mathematical/chemical way to determine why a particular oxide would be used by geologists above another. Plus, sometimes we use more than one (FeO and Fe2O3), so things can get hairy. I suspect there is no good answer and it is just "convention". We geologists have a bad habit of that! In any event, the list of oxides you created already gets me almost all the way there. I'll give it some thought and report back if I can come up with something!

Thanks again!
