### ISSUE TITLE
Getting InChI Identifier

### ISSUE THREAD

**Issue by AlanReviews** [lmmentel/mendeleev#24]
**Is your feature request related to a problem? Please describe.**
Is there a possible way to get the InChI identifier of a specific element with Mendeleev?

**Describe the solution you'd like**
Calling a function or an attribute with the InChI identifier for a specific element

**Describe alternatives you've considered**

**Additional context**

**Comment by lmmentel** [comment]
There is no functionality for InChI right now in mendeleev but as far as I understand InChI for elements are pretty straightforward to get since they would be a string with "1S/{element_symbol}". If you want to print them you could do

```python
>>> from mendeleev import He
>>> print(f"1S/{He.symbol}"
1S/He
```

Is that what you are after? Or are you talking about querying/ getting an element by InChI?

**Comment by AlanReviews** [comment]
To clarify, I am actually after finding a way to get a string to capture the InChI identifier. Your suggestion works. Thank you.
