### ISSUE TITLE
Problem with the electronic configuration

### ISSUE THREAD

**Issue by MGriot** [lmmentel/mendeleev#71]
When it comes to requesting the electronic configuration of atoms having a large number of electrons there are errors in the order in which the orbitals are given.

For example with Es the output configuration that is given is: 1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 5f11 7s2 with the following code

>>> from mendeleev import element
>>> element.(99).ec
<ElectronicConfiguration(conf="1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 5f11 7s2")>

But in theory it should be: 1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f11
I probably lack some theory but I just want to know if it's a bug or not.

## Specification

- mendeleev 0.10.0
- python 3.10.5
- Windows 10

**Comment by lmmentel** [comment]
Hi @MGriot, thanks for reporting this :raised_hands: 

As far as I can tell the difference you are referring to is only about the order the last subshells. Using the `[Rn]` to denote the Radon core it would reduce to

`[Rn] 5f11 7s2` vs `[Rn] 7s2 5f11`

If you look for example at [NIST atomic data](https://physics.nist.gov/cgi-bin/ASD/ie.pl?spectra=Es&units=1&format=0&order=0&at_num_out=on&sp_name_out=on&ion_charge_out=on&el_name_out=on&seq_out=on&shells_out=on&level_out=on&ion_conf_out=on&e_out=0&unc_out=on&biblio=on&submit=Retrieve+Data) for Es you'll find that they are reporting ground state for Es as `[Rn] 5f11 7s2` which is consistent with `mendeleev`. Could you provide a source from which you are taking the alternative configuration?

Would you mind sharing any other elements that you suspect have incorrect configurations?

**Comment by MGriot** [comment]
Hi @lmmentel, thanks for the reply 👍
Yes, the problem is exactly what you highlighted with the electronic configuration written in contracted form.
I rewrite it for convenience:
`[Rn] **5f11** 7s2` vs `[Rn] 7s2 **5f11**`

The first is the configuration I get through your library, while the second is what I would have expected. I have highlighted in bold the `f` series of atomic orbitals, precisely the part that does not come back to me.

Honestly, at first, I did not verify the sources because from what I remembered about chemistry the `f` orbitals were always filled after the `s` orbital of the next level and this happens for an energy factor.

Reading your answer I went to look for different sources in order to understand if I was missing some part of physical chemistry.
Actually, the `NIST` page shows the same configuration, with the same orders as reported by `mendeleev`. All my periodic tables also show the same electronic configurations with the same orders.

But going to look on `Wikipedia`, okay not the safest source in the world as far as the veracity of the information is concerned, the order of filling of the orbitals follows my idea.

So since both `NIST` and `mendeleev` agree with the order I think my problem is more subtle.
I, through `mendeleev`, create the electronic filling diagrams of the atomic orbitals and writing in numerical order (following the principal quantum number) does not allow me to create the graphs with the right energy order.
To understand this, I am attaching the diagram of the atomic orbitals of Ir, you will immediately notice my problem. But at this point I would say that I just have to sort the electronic configuration in terms of energy and I have solved it
![Ir](https://user-images.githubusercontent.com/20338375/185346385-b24fd095-2e6b-412e-b17b-4213e52be695.png)
.

**Comment by lmmentel** [comment]
> The other "anomalies" occur in all electronic configurations involving d and f orbitals, so almost 95% of all atoms, lol.

Since the configurations agree with NIST and you haven't provided an alternative source I'm not sure you can call them anomalies.

> So since both NIST and mendeleev agree with the order I think my problem is more subtle.
I, through mendeleev, create the electronic filling diagrams of the atomic orbitals and writing in numerical order (following the principal quantum number) does not allow me to create the graphs with the right energy order.
To understand this, I am attaching the diagram of the atomic orbitals of Ir, you will immediately notice my problem. But at this point I would say that I just have to sort the electronic configuration in terms of energy and I have solved it.

I'm not quite sure what is the problem you are describing. Could you elaborate? The electronic configuration gives you occupations of each orbitals and  only a (crude) approximation to the energy levels, so if you want to be accurate you should use spectroscopic energy levels (from e.g. NIST) but then you'll likely have to include relativistic effects for heavier elements where the Schrodinger picture is no longer accurate.

If you would like to have the configuration sorted strictly according to the [aufbau principle](https://en.wikipedia.org/wiki/Electron_configuration#Atoms:_Aufbau_principle_and_Madelung_rule) you can do that easily since the configuration is given as an ordered dict, here's an example

```python
from mendeleev import Es
from mendeleev.econf import get_l

es_conf = sorted(Es.ec.conf.items(), key=lambda x: (x[0][0] + get_l(x[0][1]), x[0][0]))
es_conf
[((1, 's'), 2),
 ((2, 's'), 2),
 ((2, 'p'), 6),
 ((3, 's'), 2),
 ((3, 'p'), 6),
 ((4, 's'), 2),
 ((3, 'd'), 10),
 ((4, 'p'), 6),
 ((5, 's'), 2),
 ((4, 'd'), 10),
 ((5, 'p'), 6),
 ((6, 's'), 2),
 ((4, 'f'), 14),
 ((5, 'd'), 10),
 ((6, 'p'), 6),
 ((7, 's'), 2),
 ((5, 'f'), 11)]
```

FYI you might want to check out the electronic structure diagrams on [ptable.com](https://ptable.com/#Electrons).

**Comment by lmmentel** [comment]
I'm happy I could help 🙂 Don't hesitate to drop any other questions you might have. 

BTW once you're finished with the visualization consider contributing it to `mendeleev` I think it would be a great addition. Good luck!

**Comment by MGriot** [comment]
Oh thank you for the proposal and above all for your availability. The intention, once finished (I write code as a hobby in my spare time), would be to make the code available. I'd like to understand how to contribute to a GitHub repository in the correct way. When I finish the code I could contact you back so I can understand how to do it.

**Comment by lmmentel** [comment]
> When I finish the code I could contact you back so I can understand how to do it.

Sure, I'm happy to help.
