### ISSUE TITLE
not all properties in fetch_table

### ISSUE THREAD

**Issue by janphhe** [lmmentel/mendeleev#90]
First: Thanks for this very nice and handy package!!
My problem: I want to use properties like the electrophility (listed under available properties). With `fetch_table('elements')` I get only 70 of the 89 listed properties, and also electrophility is missing in the output. Using 

`
from mendeleev import element
F = element('F')
F.electrophilicity()
`

gives the correct value. However, having this in the fetch_table would be much more user friendly. Is there any reason for not adding all properties to `fetch_table('elements')`?

**Comment by lmmentel** [comment]
Thanks for the feedback @janphhe.

You are right `elecrophilicity` (and some other properties) is not included when fetching data with `fetch_table`simply because `electrophilicity` is computed on the fly rather than stored in the db and `fetch_table` only reads what's in the db.

This probably isn't ideal but you could values for `electrophilicity` for all elements with

```python
from mendeleev import element
[element(i).electrophilicity() for i in range(1, 119)] 
```

In general I think it could be useful to get all the stored **and** and computed properties as a table.
