### ISSUE TITLE
It is unclear how to rebuild the database from scratch

### ISSUE THREAD

**Issue by KOLANICH** [lmmentel/mendeleev#99]
## Describe the bug
https://github.com/lmmentel/mendeleev/blob/master/mendeleev/elements.db is an SQLite database. Using third-party-provided SQLite databases is a security issue, because SQLite is not supposed to be used with adversary-controlled files. #98.

In order to mitigate the issue for now we have to generate the database ourselves with a clean and straightforward script doing so.

I have executed 

```bash
rg elements.db
```

and found https://github.com/lmmentel/mendeleev/blob/master/notebooks/glawe-pettifor.ipynb

saying
># Update the elements.db database
>Extract the Pettifor and Glawe scales from Glawe et al. 2018
>The data was extracted from the paper using [Tabula](https://tabula.technology/) and stored as csv

it seems that the data needs some postprocessing and is not all the data contained in the db.

**Comment by lmmentel** [comment]
Hey @KOLANICH, thanks for reaching out.

Could you rephrase your issue as either a question or provide more context around what outcome are you trying to achieve?

**Comment by KOLANICH** [comment]
Clarified the text a bit.

**Comment by lmmentel** [comment]
Thanks, I think I understand a bit better now.

I quite curious on what are the security restrictions not allowing you to read from a sqlitedb.

Unfortunately, there is **no way** of generating the database from original data sources since the current state is a result of ~9 years of development and data curation. 

You can however dump all the tables (either as SQL or CSV) from the `elements.db` and recreate the sqlite db yourself on a secure machine from plain text files generate by the dump. Would that be an option for you?

**Comment by KOLANICH** [comment]
>You can however dump all the tables

I can, but it would mean interfacing the database file, which is a security risk. So I prefer them to be shipped pre-dumped within either this repo, or another repo dedicated for the dataset. Maybe even `elements.sqlite` file should be `gitignore`d and people should be instructed to generate it themselves. Or, as I have said, a separate package doing everything needed during it being built.

Also I think I'd prefer if the data was in TSV files, not in SQL files doing the queries, because SQL files contain SQL queries that can do arbitrary things to the database file, but TSV files are limited, and I suspect that TSV files are safe to use that way (though it may be unsafe to open them in Excel/LO Writer). `sqlite3` CLI utility can import TSV files, so the pack to recreate the files can look like a small and clear shell script and a set of TSV files.

**Comment by lmmentel** [comment]
> I can, but it would mean interfacing the database file, which is a security risk.

If you believe the current db is compromised I would advise not to use at all. The package is MIT licensed and comes with no warranties. But I'm guessing you are also not using any other open source packages since by the same logic they (or their dependencies or the dependencies of their dependencies ... ) might be vulnerable. Unless you're going vetting all the code personally.

If not, I recommend 

```bash
sqlite3 elements.db .dump > elements.sql
```

**Comment by KOLANICH** [comment]
>Unless you're going vetting all the code personally.

Sometimes I do that. How do you think I had discovered that `mendeleev` uses `SQLite` ;) Also I use static analysers like `bandit`, that detect potentially dangerous API calls (unfortunately, not all of them).
